### ISSUE TITLE
Typfouten

### ISSUE THREAD

**Issue by DphnZwp** [Yasser-Slaymen/fdnd--free-speace#1]
Let op typfouten:
![image](https://user-images.githubusercontent.com/69635977/218827484-62185cb8-7a7b-4577-a7e1-159085a86d4f.jpeg)

![image](https://user-images.githubusercontent.com/69635977/218827497-6e5b956d-2c98-464d-85b6-b01bf2584675.jpeg)

**Comment by Yasser-Slaymen** [comment]
ik heb font-family en font -size aanpassen
