### ISSUE TITLE
2 spaties voor tabs

### ISSUE THREAD

**Issue by DphnZwp** [Yasser-Slaymen/fdnd--free-speace#2]
In je code heb je soms 4 spaties voor tabs in plaats van 2.  Stel je standaard spaties in op 2.

**Voorbeeld**
![Schermafbeelding 2023-02-15 095858](https://user-images.githubusercontent.com/69635977/218981579-a41192d4-a24e-433c-a759-a8cbe87d0055.png)

**Comment by Yasser-Slaymen** [comment]
leuk opmerking
